behaviors:
  MoveToGoal:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10000
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      # use_recurrent: true
      # sequence_length: 128
      # memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.01
        encoding_size: 128
      gail:
        strength: 1.0
        demo_path: "C:\\Users\\Adrian\\Desktop\\RL\\Assets\\Demonstrations\\DungeonRun.demo"
    behavioral_cloning:
      strength: 1.0
      demo_path: "C:\\Users\\Adrian\\Desktop\\RL\\Assets\\Demonstrations\\DungeonRun.demo"
    max_steps: 10000000000000000000000000000000
    time_horizon: 64
    summary_freq: 10000
    keep_checkpoints: 100000000000

# TRY WITH RECURRENT NEURAL NETWORKS
