behaviors:
  ShootingSpirit:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 2048
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    checkpoint_interval: 10000
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      # curiosity:
      #   gamma: 0.99
      #   strength: 0.01
      #   encoding_size: 128
    #   gail:
    #     strength: 0.15
    #     demo_path: "C:\\Users\\Adrian\\Desktop\\RL\\Assets\\Demonstrations\\DungeonRunExtend.demo"
    # behavioral_cloning:
    #   strength: 0.2
    #   demo_path: "C:\\Users\\Adrian\\Desktop\\RL\\Assets\\Demonstrations\\DungeonRunExtend.demo"
    max_steps: 10000000000000000000000000000000
    time_horizon: 64
    summary_freq: 1024
    keep_checkpoints: 100000000000
